### ISSUE TITLE
Finalize Posters + Speakers

### ISSUE THREAD

**Issue by ebryson2** [Network-Goods/PL-Research-Symposium#16]
- [ ] [Identify proposal reviewers](https://github.com/Network-Goods/PL-Research-Symposium/issues/15)
- [ ] [Potential speaker outreach](https://github.com/Network-Goods/PL-Research-Symposium/issues/18)
- [ ] [Final decision on proposals](https://github.com/Network-Goods/PL-Research-Symposium/issues/17)
